"""add 'days_to_hire' table

Revision ID: bd5356be7d29
Revises: 991ecb2bf269
Create Date: 2025-06-13 03:07:15.031203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd5356be7d29'
down_revision = '991ecb2bf269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_to_hire',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('standard_job_id', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('avg_days', sa.Float(), nullable=False),
    sa.Column('min_days', sa.Float(), nullable=False),
    sa.Column('max_days', sa.Float(), nullable=False),
    sa.Column('job_postings', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('standard_job_id', 'country_code', name='uq_stdjob_country'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days_to_hire', schema='public')
    # ### end Alembic commands ###
